import Head from "next/head";
import { Inter } from "@next/font/google";
import { HomeContent } from "@/screens/home/home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>visio meeting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen bg-primary ">
        <HomeContent />
      </main>
    </>
  );
}
